name: Build on ARMv8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        load: true # Remove push and add load to load the image into Docker after build
        tags: ubuntu

    - name: Build project
      run: |
        make

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-files
        path: ./
