name: Cross Compile

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install cross compiler
      run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
      
    - name: check gcc
      run: gcc-aarch64-linux-gnu --version && sudo find / -name gcc-aarch64-linux-gnu
      
    - name: Compile
      run: |
        make
